<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width"/>
    <meta name="viewport" content="initial-scale=1.0"/>
    <meta name="robots" content="index, follow"/>
    <meta name="description" content="">
    <meta name="keywords" content="">

    
    <link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/>
    <link type="text/css" rel="stylesheet" href="css/ghpages-materialize.css"  media="screen,projection"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col s6 push-s2">
                <h1>Mystic Labs</h1>
            </div>
        </div>
        <div class="row"
            <form class="col s12">
                <div class="col s12 m6">
                    <div class="card">
                        <div class="card-content ">
                            <div class="card-action">
                                <div class="row">
                                    <div class="col s12">
                                        <input placeholder="" id="username" name="username" type="text" class="validate" autofocus>
                                        <label for="username">Username</label>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col s12">
                                        <input placeholder="********" id="password" name="password" type="password" class="validate">
                                        <label for="password">Password</label>
                                    </div>
                                </div>
                                <div class="row">
                                
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script type="text/javascript" src="js/materialize.min.js"></script>
</body>
</html>